Added updateConfig function
GoogleChromeLabs/bubblewrap pull request #293
Opened 2020-08-19 12:29 UTC by chenlevy24

2020-08-19 13:38 UTC, andreban requested changes
A few small changes.

2020-08-19 13:38 UTC, andreban commented on packages/cli/src/lib/cmds/updateConfig.ts
> +const CONFIG_FILE_PATH = join(homedir(), '.bubblewrap-config/bubblewrap-config.json');
We should probably use the constants from `config.ts` and avoid duplication.

2020-08-19 13:38 UTC, andreban commented on packages/cli/src/lib/cmds/updateConfig.ts
> +  const jdkPath = (await config).jdkPath;
It's more idiomatic to move the `await` call to the line above where we are calling `loadOrCreateConfig`. So:
 
```ts
const config = await loadOrCreateConfig();
const jdkPath = config.jdkPath;
```

2020-08-19 13:38 UTC, andreban commented on packages/cli/src/lib/cmds/updateConfig.ts
> +  const androidSdkPath = (await config).androidSdkPath;
We have already called `await` on the line above. This line can be just:
```suggestion
  const androidSdkPath = config.androidSdkPath;
```

2020-08-19 13:38 UTC, andreban commented on packages/cli/src/lib/cmds/updateConfig.ts
> +  return await invoke(args, log);
All `updateConfig` is doing right now is call `invoke`. Maybe the logic from `invoke` could be added directly to `updateConfig`? Or are we planning to make `updateConfig` more complex later?

2020-08-19 14:35 UTC, andreban approved these changes
LGTM, Thank you.

2020-08-20 08:38 UTC, merged

2020-08-20 08:39 UTC, PEConn approved these changes

2020-10-11 03:27 UTC, MrVibe commented
please add 1 sample line on how to use it.  Getting this error "updateConfig ERROR Usage"