Added svg support
GoogleChromeLabs/bubblewrap pull request #341
Opened 2020-09-23 06:52 UTC by chenlevy24

Changed `ImageHelper` and `util` to support svg type images.

2020-09-23 08:09 UTC, PEConn approved these changes
This is looking great, thanks!

2020-09-23 08:09 UTC, PEConn commented on packages/core/src/lib/wrappers/svg2img.ts
> +export enum Format {
Do you mind adding a comment somewhere in this class that they're only reason we're doing this is that we couldn't get their types to work, and that if we do in the future, we can remove most of this.

2020-09-23 10:00 UTC, andreban requested changes
Generally looks good. Dropped some notes.

2020-09-23 10:05 UTC, chenlevy24 commented on packages/core/src/lib/wrappers/svg2img.ts
> +const _svg2img = require('svg2img');
it isn't working

2020-09-23 10:34 UTC, chenlevy24 commented on packages/core/src/lib/wrappers/svg2img.ts
> +export type Callback = (err: any, buffer: any) => any;
I just removed it, it being used in only one place so there is no need for a special type

2020-09-25 12:42 UTC, andreban approved these changes
LGTM, Thank you!

2020-09-30 07:32 UTC, merged

2020-11-04 18:48 UTC, JudahGabriel commented
Is this available in a stable Bubblewrap release?

2020-11-04 20:31 UTC, andreban commented
This has been published on 1.7.0 (https://github.com/GoogleChromeLabs/bubblewrap/releases/tag/v1.7.0)